/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class immersiveaudio_fmod_IVNative */

#ifndef _Included_immersiveaudio_fmod_IVNative
#define _Included_immersiveaudio_fmod_IVNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     immersiveaudio_fmod_IVNative
 * Method:    Init_IV
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_immersiveaudio_fmod_IVNative_Init_1IV
  (JNIEnv *env, jclass clazz, jlong voip_channel_group);

/*
 * Class:     immersiveaudio_fmod_IVNative
 * Method:    FMOD_Channel_AddDSP
 * Signature: (JIJ)I
 */
JNIEXPORT jint JNICALL Java_immersiveaudio_fmod_IVNative_FMOD_1Channel_1AddDSP
  (JNIEnv *env, jclass clazz, jlong channel_addr, jint index, jlong dsp_addr);

/*
 * Class:     immersiveaudio_fmod_IVNative
 * Method:    FMOD_Channel_RemoveDSP
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_immersiveaudio_fmod_IVNative_FMOD_1Channel_1RemoveDSP
  (JNIEnv *env, jclass clazz, jlong channel_addr, jlong dsp_addr);

/*
 * Class:     immersiveaudio_fmod_IVNative
 * Method:    FMOD_Channel_GetNumDSPs
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_immersiveaudio_fmod_IVNative_FMOD_1Channel_1GetNumDSPs
(JNIEnv *env, jclass clazz, jlong channel_addr);

/*
 * Class:     immersiveaudio_fmod_IVNative
 * Method:    FMOD_Channel_GetDSP
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_immersiveaudio_fmod_IVNative_FMOD_1Channel_1GetDSP
(JNIEnv *env, jclass clazz, jlong channel_addr, jint index);

/*
 * Class:     immersiveaudio_fmod_IVNative
 * Method:    FMOD_ChannelGroup_AddDSP
 * Signature: (JIJ)I
 */
JNIEXPORT jint JNICALL Java_immersiveaudio_fmod_IVNative_FMOD_1ChannelGroup_1AddDSP
  (JNIEnv *env, jclass clazz, jlong channelgroup_addr, jint index, jlong dsp_addr);

/*
 * Class:     immersiveaudio_fmod_IVNative
 * Method:    FMOD_ChannelGroup_RemoveDSP
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_immersiveaudio_fmod_IVNative_FMOD_1ChannelGroup_1RemoveDSP
  (JNIEnv *env, jclass clazz, jlong channelgroup_addr, jlong dsp_addr);

/*
 * Class:     immersiveaudio_fmod_IVNative
 * Method:    FMOD_ChannelGroup_GetNumDSPs
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_immersiveaudio_fmod_IVNative_FMOD_1ChannelGroup_1GetNumDSPs
(JNIEnv *env, jclass clazz, jlong channel_group_addr);

/*
 * Class:     immersiveaudio_fmod_IVNative
 * Method:    FMOD_ChannelGroup_GetDSP
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_immersiveaudio_fmod_IVNative_FMOD_1ChannelGroup_1GetDSP
(JNIEnv* env, jclass clazz, jlong channel_group_addr , jint index);

/*
 * Class:     immersiveaudio_fmod_IVNative
 * Method:    FMOD_DSP_GetActive
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_immersiveaudio_fmod_IVNative_FMOD_1DSP_1GetActive
  (JNIEnv *env, jclass clazz, jlong dsp_addr);

/*
 * Class:     immersiveaudio_fmod_IVNative
 * Method:    FMOD_DSP_GetBypass
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_immersiveaudio_fmod_IVNative_FMOD_1DSP_1GetBypass
  (JNIEnv *env, jclass clazz, jlong dsp_addr);

/*
 * Class:     immersiveaudio_fmod_IVNative
 * Method:    FMOD_DSP_SetActive
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_immersiveaudio_fmod_IVNative_FMOD_1DSP_1SetActive
  (JNIEnv *env, jclass clazz, jlong dsp_addr, jboolean active);

/*
 * Class:     immersiveaudio_fmod_IVNative
 * Method:    FMOD_DSP_SetBypass
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_immersiveaudio_fmod_IVNative_FMOD_1DSP_1SetBypass
  (JNIEnv *env, jclass clazz, jlong dsp_addr, jboolean bypass);

/*
 * Class:     immersiveaudio_fmod_IVNative
 * Method:    FMOD_DSP_SetParameterFloat
 * Signature: (JIF)I
 */
JNIEXPORT jint JNICALL Java_immersiveaudio_fmod_IVNative_FMOD_1DSP_1SetParameterFloat
  (JNIEnv *env, jclass clazz, jlong dsp_addr, jint index, jfloat value);

/*
 * Class:     immersiveaudio_fmod_IVNative
 * Method:    FMOD_DSP_GetParameterFloat
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_immersiveaudio_fmod_IVNative_FMOD_1DSP_1GetParameterFloat
  (JNIEnv *env, jclass clazz, jlong dsp_addr, jint index);

/*
 * Class:     immersiveaudio_fmod_IVNative
 * Method:    FMOD_DSP_SetParameterInt
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_immersiveaudio_fmod_IVNative_FMOD_1DSP_1SetParameterInt
  (JNIEnv *env, jclass clazz, jlong dsp_addr, jint index, jint value);

/*
 * Class:     immersiveaudio_fmod_IVNative
 * Method:    FMOD_DSP_GetParameterInt
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_immersiveaudio_fmod_IVNative_FMOD_1DSP_1GetParameterInt
  (JNIEnv *env, jclass clazz, jlong dsp_addr, jint index);

/*
 * Class:     immersiveaudio_fmod_IVNative
 * Method:    FMOD_DSP_SetParameterBool
 * Signature: (JIZ)I
 */
JNIEXPORT jint JNICALL Java_immersiveaudio_fmod_IVNative_FMOD_1DSP_1SetParameterBool
  (JNIEnv *env, jclass clazz, jlong dsp_addr, jint index, jboolean value);

/*
 * Class:     immersiveaudio_fmod_IVNative
 * Method:    FMOD_DSP_GetParameterBool
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_immersiveaudio_fmod_IVNative_FMOD_1DSP_1GetParameterBool
  (JNIEnv *env, jclass clazz, jlong dsp_addr, jint index);

/*
 * Class:     immersiveaudio_fmod_IVNative
 * Method:    FMOD_DSP_Release
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_immersiveaudio_fmod_IVNative_FMOD_1DSP_1Release
  (JNIEnv *env, jclass clazz, jlong dsp_addr);

/*
 * Class:     immersiveaudio_fmod_IVNative
 * Method:    FMOD_System_CreateDSPByType
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_immersiveaudio_fmod_IVNative_FMOD_1System_1CreateDSPByType
  (JNIEnv *env, jclass clazz, jint dsp_type);

/*
 * Class:     immersiveaudio_fmod_IVNative
 * Method:    FMOD_DSP_GetNumParameters
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_immersiveaudio_fmod_IVNative_FMOD_1DSP_1GetNumParameters
(JNIEnv *env, jclass clazz, jlong dsp_addr);

/*
 * Class:     immersiveaudio_fmod_IVNative
 * Method:    FMOD_DSP_AddInput
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_immersiveaudio_fmod_IVNative_FMOD_1DSP_1AddInput
(JNIEnv *env, jclass clazz, jlong dsp_addr, jlong input_dsp_addr);

/*
 * Class:     immersiveaudio_fmod_IVNative
 * Method:    FMOD_System_SetReverbProperties
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_immersiveaudio_fmod_IVNative_FMOD_1System_1SetReverbProperties
(JNIEnv* env, jclass clazz, jint instance, jint preset);

#ifdef __cplusplus
}
#endif
#endif
