package immersivevoip.fmod;

// fmod enums and defs
public class IVFMOD {
    public IVFMOD(){

    }

    public enum FMOD_DSP_TYPE {
        FMOD_DSP_TYPE_UNKNOWN,
        FMOD_DSP_TYPE_MIXER,
        FMOD_DSP_TYPE_OSCILLATOR,
        FMOD_DSP_TYPE_LOWPASS,
        FMOD_DSP_TYPE_ITLOWPASS,
        FMOD_DSP_TYPE_HIGHPASS,
        FMOD_DSP_TYPE_ECHO,
        FMOD_DSP_TYPE_FADER,
        FMOD_DSP_TYPE_FLANGE,
        FMOD_DSP_TYPE_DISTORTION,
        FMOD_DSP_TYPE_NORMALIZE,
        FMOD_DSP_TYPE_LIMITER,
        FMOD_DSP_TYPE_PARAMEQ,
        FMOD_DSP_TYPE_PITCHSHIFT,
        FMOD_DSP_TYPE_CHORUS,
        FMOD_DSP_TYPE_VSTPLUGIN,
        FMOD_DSP_TYPE_WINAMPPLUGIN,
        FMOD_DSP_TYPE_ITECHO,
        FMOD_DSP_TYPE_COMPRESSOR,
        FMOD_DSP_TYPE_SFXREVERB,
        FMOD_DSP_TYPE_LOWPASS_SIMPLE,
        FMOD_DSP_TYPE_DELAY,
        FMOD_DSP_TYPE_TREMOLO,
        FMOD_DSP_TYPE_LADSPAPLUGIN,
        FMOD_DSP_TYPE_SEND,
        FMOD_DSP_TYPE_RETURN,
        FMOD_DSP_TYPE_HIGHPASS_SIMPLE,
        FMOD_DSP_TYPE_PAN,
        FMOD_DSP_TYPE_THREE_EQ,
        FMOD_DSP_TYPE_FFT,
        FMOD_DSP_TYPE_LOUDNESS_METER,
        FMOD_DSP_TYPE_ENVELOPEFOLLOWER,
        FMOD_DSP_TYPE_CONVOLUTIONREVERB,
        FMOD_DSP_TYPE_CHANNELMIX,
        FMOD_DSP_TYPE_TRANSCEIVER,
        FMOD_DSP_TYPE_OBJECTPAN,
        FMOD_DSP_TYPE_MULTIBAND_EQ,
        FMOD_DSP_TYPE_MAX
    }

    public enum FMOD_DSP_DISTORTION {
        FMOD_DSP_DISTORTION_LEVEL
    }

    public enum FMOD_DSP_THREE_EQ {
        FMOD_DSP_THREE_EQ_LOWGAIN,
        FMOD_DSP_THREE_EQ_MIDGAIN,
        FMOD_DSP_THREE_EQ_HIGHGAIN,
        FMOD_DSP_THREE_EQ_LOWCROSSOVER,
        FMOD_DSP_THREE_EQ_HIGHCROSSOVER,
        FMOD_DSP_THREE_EQ_CROSSOVERSLOPE
    }

    public enum FMOD_DSP_COMPRESSOR {
        FMOD_DSP_COMPRESSOR_THRESHOLD,
        FMOD_DSP_COMPRESSOR_RATIO,
        FMOD_DSP_COMPRESSOR_ATTACK,
        FMOD_DSP_COMPRESSOR_RELEASE,
        FMOD_DSP_COMPRESSOR_GAINMAKEUP,
        FMOD_DSP_COMPRESSOR_USESIDECHAIN,
        FMOD_DSP_COMPRESSOR_LINKED
    }

    public enum FMOD_DSP_OSCILLATOR {
        FMOD_DSP_OSCILLATOR_TYPE,
        FMOD_DSP_OSCILLATOR_RATE
    }

    public enum FMOD_DSP_FADER{
        FMOD_DSP_FADER_GAIN,
        FMOD_DSP_FADER_OVERALL_GAIN
    }

    public enum FMOD_REVERB_PRESET {
        FMOD_PRESET_OFF,
        FMOD_PRESET_GENERIC,
        FMOD_PRESET_PADDEDCELL,
        FMOD_PRESET_ROOM,
        FMOD_PRESET_BATHROOM,
        FMOD_PRESET_LIVINGROOM,
        FMOD_PRESET_STONEROOM,
        FMOD_PRESET_AUDITORIUM,
        FMOD_PRESET_CONCERTHALL,
        FMOD_PRESET_CAVE,
        FMOD_PRESET_ARENA,
        FMOD_PRESET_HANGAR,
        FMOD_PRESET_CARPETTEDHALLWAY,
        FMOD_PRESET_HALLWAY,
        FMOD_PRESET_STONECORRIDOR,
        FMOD_PRESET_ALLEY,
        FMOD_PRESET_FOREST,
        FMOD_PRESET_CITY,
        FMOD_PRESET_MOUNTAINS,
        FMOD_PRESET_QUARRY,
        FMOD_PRESET_PLAIN,
        FMOD_PRESET_PARKINGLOT,
        FMOD_PRESET_SEWERPIPE,
        FMOD_PRESET_UNDERWATER
    }
}
